# Builds dev-machine from specified Dockerfile
# Intended for development and testing of dev-machine image
projectdb:
    image: ff0000/db-machine:latest
    environment: 
        REPLICATION_ROLE: standalone
        DATABASE: project_database
        POSTGRES_PASSWORD: IAMNOTSECURE
        # Let not connect as the postgres user .. that'd be bad.
        PROJECT_USER: project_user
        PROJECT_PASSWORD: IAMNOTSECURE
    ports:
        - "5432:5432"
projectredis:
    image: redis:3
projectdev:
    build: dev-machine
    command: /bin/bash
    name: projectdev
    tty: true
    stdin_open: true
    volumes:
        - ../:/srv/active
    ports:
        - "8000:8000"
        - "3001:3001"
        - "3000:3000"
    links:
        - projectdb
        - projectredis
