jenkins-server:
  build: .
  container_name: jenkins-server
  hostname: jenkins-server
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    JENKINS_OPTS: "--handlerCountStartup=100 --handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - ./jenkins_data:/var/jenkins_home