# Builds dev-machine from specified Dockerfile
# Intended for development and testing of dev-machine image
projectdev:
    build: base-machine
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
        - ../../:/srv/active
